# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_block_cpp <- function(ann) {
    .Call('_SGNB_create_block_cpp', PACKAGE = 'SGNB', ann)
}

create_read_type_cpp <- function(input_sam_path, block_ann, gene_range, min_overlap) {
    .Call('_SGNB_create_read_type_cpp', PACKAGE = 'SGNB', input_sam_path, block_ann, gene_range, min_overlap)
}

create_read_type_group_cpp <- function(read_gene_unique_vec, read_gene_vec, read_type_vec, min_reduce) {
    .Call('_SGNB_create_read_type_group_cpp', PACKAGE = 'SGNB', read_gene_unique_vec, read_gene_vec, read_type_vec, min_reduce)
}

fit_SGNB_cpp <- function(read_gene_unique_vec, read_gene_vec, phi, data_matrix, lib_size_norm, group_sample_num, gene_size_ls, tol, times) {
    .Call('_SGNB_fit_SGNB_cpp', PACKAGE = 'SGNB', read_gene_unique_vec, read_gene_vec, phi, data_matrix, lib_size_norm, group_sample_num, gene_size_ls, tol, times)
}

fit_SGNB_exact_cpp <- function(read_gene_vec, read_type_vec, data_matrix, lib_size_norm, group_sample_num, tol, times) {
    .Call('_SGNB_fit_SGNB_exact_cpp', PACKAGE = 'SGNB', read_gene_vec, read_type_vec, data_matrix, lib_size_norm, group_sample_num, tol, times)
}

