# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gen_pseudo <- function(data, lib_size_norm, group_sample_num, init_delta, m, tol, times) {
    .Call('SGNB_gen_pseudo', PACKAGE = 'SGNB', data, lib_size_norm, group_sample_num, init_delta, m, tol, times)
}

exact_test <- function(pseudo_data, delta, group_sample_num, side) {
    .Call('SGNB_exact_test', PACKAGE = 'SGNB', pseudo_data, delta, group_sample_num, side)
}

create_block_cpp <- function(ann) {
    .Call('SGNB_create_block_cpp', PACKAGE = 'SGNB', ann)
}

create_read_type_cpp <- function(input_sam_path, block_ann, gene_range, min_overlap) {
    .Call('SGNB_create_read_type_cpp', PACKAGE = 'SGNB', input_sam_path, block_ann, gene_range, min_overlap)
}

create_read_type_group_cpp <- function(read_gene_unique_vec, read_gene_vec, read_type_vec, min_reduce) {
    .Call('SGNB_create_read_type_group_cpp', PACKAGE = 'SGNB', read_gene_unique_vec, read_gene_vec, read_type_vec, min_reduce)
}

fit_SGNB_cpp <- function(read_gene_unique_vec, read_gene_vec, data_matrix, lib_size_norm, group_sample_num, gene_size_ls, tol, times) {
    .Call('SGNB_fit_SGNB_cpp', PACKAGE = 'SGNB', read_gene_unique_vec, read_gene_vec, data_matrix, lib_size_norm, group_sample_num, gene_size_ls, tol, times)
}

fit_SGNB_exact_cpp <- function(read_gene_vec, read_type_vec, data_matrix, lib_size_norm, group_sample_num, tol, times, side) {
    .Call('SGNB_fit_SGNB_exact_cpp', PACKAGE = 'SGNB', read_gene_vec, read_type_vec, data_matrix, lib_size_norm, group_sample_num, tol, times, side)
}

